title: <p align = 'center' > Kaylyn Vo </p>

logo: "/images/picture.png?raw=true" 

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align = 'center'>
  <a href="https://www.linkedin.com/in/kaylyn-vo-244b0017a/">LinkedIn</a>| 
  <a href='https://github.com/vkaylyn'>GiHub</a>|
  <a href='https://github.com/vkaylyn/vkaylyn.github.io/blob/main/VoKaylynResume.pdf'>Resume</a>|
  
  <p align='justify'>
  I am a second year Master's Student of Statistics at San Jose State University.
  <br><br>
  <a href="https://www.linkedin.com/in/example/"a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

